---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: flaskapp

spec:

# Number of Replica
  replicas: 1

# This must match the labels we set on the pod!
  selector:
    matchLabels:
      app: flaskapp
      tier: app
# This template field is a regular pod configuration
  template:
    metadata:
      labels:
        app: flaskapp
        tier: app

# Pod configuration
    spec:
      containers:
        - name: flaskapp
          image: ankurpatel/nflapp:latest
          imagePullPolicy: Always
          env:
            - name: DB_User
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
            - name: DB_Host
              value: mysql
          ports:
            - name: flaskapp
              containerPort: 5000
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    service: flaskapp

spec:
  type: NodePort                            # Opens specific port on VMs
  selector:
    app: flaskapp                           # Select pods with the label 'app' set to 'flaskapp'
  ports:
    - port: 5000                            # port exposed internally in the cluster
      targetPort: 5000                      # the container port to send requests to
      nodePort: 30036                       # a static port assigned on each the node/VMs

