apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flaskapp-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/flaskapp
