apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: ankurpatel/nfldb:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: /tmp/mysql

      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
