apiVersion: v1
kind: Service

metadata:
  name: mysql
  labels:
    service: mysql

spec:
  type: ClusterIP                     # A virtual ip to access from any nodes in the cluster
  ports:
    - port: 3306                      # port exposed internally in the cluster
      targetPort: 3306                # the container port to send requests to
  selector:
    app: mysql
