---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: ankurpatel/db:$BUILD_NUMBER
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pv
              mountPath: /tmp/mysql

      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service

metadata:
  name: mysql
  labels:
    service: mysql

spec:
  type: ClusterIP                     
  ports:
    - port: 3306                      
      targetPort: 3306                
  selector:
    app: mysql